services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/dockerfile
    container_name: auth_service
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./auth_service/.env
    
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ./auth_service/.env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: